/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.table.store.table.sink;

import org.apache.flink.table.store.annotation.Experimental;
import org.apache.flink.table.store.table.Table;

import java.util.List;
import java.util.Set;

/**
 * Create and commit snapshots of a {@link Table}. Snapshots are produced from {@link
 * CommitMessage}s, which themselves are generated by {@link TableWrite}. Also see {@link
 * TableWrite#prepareCommit}.
 *
 * <p>Commit may fail and throw an exception. Before committing, it will first check for conflicts
 * by checking if all files to be removed currently exists.
 *
 * @since 0.4.0
 */
@Experimental
public interface TableCommit extends AutoCloseable {

    /**
     * Default ignore empty commit, if this is set to false, when there is no new data, an empty
     * commit will also be created.
     *
     * <p>NOTE: It is recommended to set 'ignoreEmptyCommit' to false in streaming write, in order
     * to better remove duplicate commits (See {@link #filterCommitted}).
     */
    TableCommit ignoreEmptyCommit(boolean ignoreEmptyCommit);

    /**
     * Filter committed commits. Return uncommitted identifiers. This method is used for failover
     * cases.
     */
    Set<Long> filterCommitted(Set<Long> commitIdentifiers);

    /**
     * Create a new commit. One commit may generate up to two snapshots, one for adding new files
     * and the other for compaction. There will be some expiration policies after commit:
     *
     * <p>1. Snapshot expiration may occur according to three options:
     *
     * <ul>
     *   <li>'snapshot.time-retained': The maximum time of completed snapshots to retain.
     *   <li>'snapshot.num-retained.min': The minimum number of completed snapshots to retain.
     *   <li>'snapshot.num-retained.max': The maximum number of completed snapshots to retain.
     * </ul>
     *
     * <p>2. Partition expiration may occur according to 'partition.expiration-time'. The partition
     * check is expensive, so all partitions are not checked every time when invoking this method.
     * The check frequency is controlled by 'partition.expiration-check-interval'. Partition
     * expiration will create an 'OVERWRITE' snapshot.
     *
     * @param commitIdentifier Committed transaction ID, can start from 0. If there are multiple
     *     commits, please increment this ID.
     * @param commitMessages commit messages from table write
     * @see TableWrite#prepareCommit
     */
    void commit(long commitIdentifier, List<CommitMessage> commitMessages);
}
