openapi: 3.0.1
info:
  title: RESTCatalog API
  description: This API exposes endpoints to RESTCatalog.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
  - url: http://localhost:8080
    description: Server URL in Development environment
paths:
  /api/v1/{prefix}/databases:
    get:
      tags:
        - database
      summary: List Databases
      operationId: listDatabases
      parameters:
        - name: prefix
          in: path
          required: true
          schema:
            type: string
      responses:
        "500":
          description: Internal Server Error
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDatabasesResponse'
    post:
      tags:
        - database
      summary: Create Databases
      operationId: createDatabases
      parameters:
        - name: prefix
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDatabaseRequest'
      responses:
        "500":
          description: Internal Server Error
        "409":
          description: Resource has exist
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDatabaseResponse'
  /api/v1/{prefix}/databases/{database}:
    get:
      tags:
        - database
      summary: Get Database
      operationId: getDatabases
      parameters:
        - name: prefix
          in: path
          required: true
          schema:
            type: string
        - name: database
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDatabaseResponse'
        "404":
          description: Resource not found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal Server Error
    delete:
      tags:
        - database
      summary: Drop Database
      operationId: dropDatabases
      parameters:
        - name: prefix
          in: path
          required: true
          schema:
            type: string
        - name: database
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DropDatabaseRequest'
      responses:
        "404":
          description: Resource not found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal Server Error
  /api/v1/config:
    get:
      tags:
        - config
      summary: Get Config
      operationId: getConfig
      responses:
        "500":
          description: Internal Server Error
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigResponse'
components:
  schemas:
    CreateDatabaseRequest:
      type: object
      properties:
        name:
          type: string
        ignoreIfExists:
          type: boolean
        options:
          type: object
          additionalProperties:
            type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
          format: int32
        stack:
          type: array
          items:
            type: string
    CreateDatabaseResponse:
      type: object
      properties:
        name:
          type: string
        options:
          type: object
          additionalProperties:
            type: string
    DatabaseName:
      type: object
      properties:
        name:
          type: string
    ListDatabasesResponse:
      type: object
      properties:
        databases:
          type: array
          items:
            $ref: '#/components/schemas/DatabaseName'
    GetDatabaseResponse:
      type: object
      properties:
        name:
          type: string
        options:
          type: object
          additionalProperties:
            type: string
    ConfigResponse:
      type: object
      properties:
        defaults:
          type: object
          additionalProperties:
            type: string
        overrides:
          type: object
          additionalProperties:
            type: string
    DropDatabaseRequest:
      type: object
      properties:
        ignoreIfNotExists:
          type: boolean
        cascade:
          type: boolean
