/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.paimon.operation.commit;

import org.apache.paimon.Snapshot;
import org.apache.paimon.manifest.FileKind;
import org.apache.paimon.manifest.ManifestEntry;
import org.apache.paimon.utils.RangeHelper;

import java.util.List;
import java.util.stream.Collectors;

/** Utils for data evolution commit. */
public class DataEvolutionCommitUtils {

    /**
     * To calculate the delta record count of data evolution. We cannot determine row count changes
     * based solely on delta files. For example, delta files generated by INSERT OVERWRITE and
     * compaction operations both contain ADD and DELETE records.
     */
    public static long dataEvolutionDeltaRecordCount(
            List<ManifestEntry> deltaFiles, long insertedRowNum, Snapshot.CommitKind commitKind) {
        if (commitKind == Snapshot.CommitKind.COMPACT) {
            return 0;
        }

        // Delete files could be produced by INSERT OVERWRITE and Drop partition operations.
        // When reaches here, delete files should not contain partial records.
        return insertedRowNum - dataEvolutionRecordCount(deltaFiles, FileKind.DELETE);
    }

    public static long dataEvolutionRecordCount(
            List<ManifestEntry> manifestEntries, FileKind kind) {
        List<ManifestEntry> entries =
                manifestEntries.stream().filter(e -> e.kind() == kind).collect(Collectors.toList());

        long sum = 0L;
        RangeHelper<ManifestEntry> rangeHelper =
                new RangeHelper<>(entry -> entry.file().nonNullRowIdRange());
        List<List<ManifestEntry>> ranges = rangeHelper.mergeOverlappingRanges(entries);
        for (List<ManifestEntry> group : ranges) {
            long maxCount = 0;
            for (ManifestEntry file : group) {
                maxCount = Math.max(maxCount, file.rowCount());
            }
            sum += maxCount;
        }
        return sum;
    }
}
