/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated by javah */
#ifndef _Included_org_apache_paimon_faiss_jni_FaissJNI
#define _Included_org_apache_paimon_faiss_jni_FaissJNI

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    createIndex
 * Signature: (ILjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_createIndex
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    createHnswIndex
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_createHnswIndex
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    createIvfIndex
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_createIvfIndex
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    createIvfPqIndex
 * Signature: (IIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_createIvfPqIndex
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    addVectors
 * Signature: (J[FI)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_addVectors
  (JNIEnv *, jclass, jlong, jfloatArray, jint);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    addVectorsWithIds
 * Signature: (J[F[JI)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_addVectorsWithIds
  (JNIEnv *, jclass, jlong, jfloatArray, jlongArray, jint);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    trainIndex
 * Signature: (J[FI)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_trainIndex
  (JNIEnv *, jclass, jlong, jfloatArray, jint);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    isTrained
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_isTrained
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    search
 * Signature: (J[FII[F[J)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_search
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint, jfloatArray, jlongArray);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    rangeSearch
 * Signature: (J[FIF)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_rangeSearch
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jfloat);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    setHnswEfSearch
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_setHnswEfSearch
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    setIvfNprobe
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_setIvfNprobe
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    getIndexSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_getIndexSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    getIndexDimension
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_getIndexDimension
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    writeIndex
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_writeIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    readIndex
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_readIndex
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    freeIndex
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_freeIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    resetIndex
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_resetIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_paimon_faiss_jni_FaissJNI
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_paimon_faiss_jni_FaissJNI_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif

#endif


