/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.paimon.globalindex.btree;

import org.apache.paimon.data.BinaryRow;
import org.apache.paimon.manifest.IndexManifestEntry;
import org.apache.paimon.utils.Range;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * A compaction task for BTree global index.
 *
 * <p>Each task represents one contiguous segment of range groups that should be merged together.
 * Generated by {@link BTreeGlobalIndexCompactCoordinator} and executed by {@link
 * BTreeGlobalIndexCompactWorker}.
 */
public class BTreeGlobalIndexCompactTask implements Serializable {

    private static final long serialVersionUID = 1L;

    private final BinaryRow partition;
    private final int bucket;
    private final String indexType;
    private final int indexFieldId;
    private final List<RangeGroup> rangeGroups;
    private final Range mergedRange;

    public BTreeGlobalIndexCompactTask(
            BinaryRow partition,
            int bucket,
            String indexType,
            int indexFieldId,
            List<RangeGroup> rangeGroups,
            Range mergedRange) {
        this.partition = partition;
        this.bucket = bucket;
        this.indexType = indexType;
        this.indexFieldId = indexFieldId;
        this.rangeGroups = rangeGroups;
        this.mergedRange = mergedRange;
    }

    public BinaryRow partition() {
        return partition;
    }

    public int bucket() {
        return bucket;
    }

    public String indexType() {
        return indexType;
    }

    public int indexFieldId() {
        return indexFieldId;
    }

    public List<RangeGroup> rangeGroups() {
        return rangeGroups;
    }

    public Range mergedRange() {
        return mergedRange;
    }

    /** All source entries across all range groups in this task. */
    public List<IndexManifestEntry> sourceEntries() {
        List<IndexManifestEntry> entries = new ArrayList<>();
        for (RangeGroup group : rangeGroups) {
            entries.addAll(group.files());
        }
        return entries;
    }

    @Override
    public String toString() {
        return "BTreeGlobalIndexCompactTask{"
                + "partition="
                + partition
                + ", bucket="
                + bucket
                + ", indexType='"
                + indexType
                + '\''
                + ", indexFieldId="
                + indexFieldId
                + ", mergedRange="
                + mergedRange
                + ", rangeGroupCount="
                + rangeGroups.size()
                + '}';
    }

    /** A group of index files sharing the same row range. */
    public static class RangeGroup implements Serializable {

        private static final long serialVersionUID = 1L;

        private final Range range;
        private final List<IndexManifestEntry> files;

        public RangeGroup(Range range, List<IndexManifestEntry> files) {
            this.range = range;
            this.files = files;
        }

        public Range range() {
            return range;
        }

        public List<IndexManifestEntry> files() {
            return files;
        }
    }
}
