name: 'Setup FAISS'
description: 'Install native dependencies and build FAISS library'

runs:
  using: "composite"
  steps:
    - name: Install native dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libopenblas-dev \
          liblapack-dev \
          patchelf \
          libgomp1 \
          wget

    - name: Install GCC 9
      shell: bash
      run: |
        sudo apt-get install -y gcc-9 g++-9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
        gcc --version
        g++ --version
        # Verify GCC version is >= 9.3.0
        # Use -dumpfullversion for full version, fall back to -dumpversion
        GCC_VERSION=$(gcc -dumpfullversion 2>/dev/null || gcc -dumpversion)
        echo "GCC version: $GCC_VERSION"
        # Extract major version
        GCC_MAJOR=$(echo "$GCC_VERSION" | cut -d. -f1)
        if [[ "$GCC_MAJOR" -lt 9 ]]; then
          echo "ERROR: GCC major version must be >= 9, got $GCC_MAJOR"
          exit 1
        fi
        echo "GCC version check passed: $GCC_VERSION (major: $GCC_MAJOR)"

    - name: Install CMake 3.30.1
      shell: bash
      run: |
        CMAKE_VERSION="3.30.1"
        wget -q https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz
        tar -xzf cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz
        sudo mv cmake-${CMAKE_VERSION}-linux-x86_64 /opt/cmake
        sudo ln -sf /opt/cmake/bin/cmake /usr/local/bin/cmake
        sudo ln -sf /opt/cmake/bin/ctest /usr/local/bin/ctest
        sudo ln -sf /opt/cmake/bin/cpack /usr/local/bin/cpack
        cmake --version
        # Verify CMake version
        CMAKE_INSTALLED=$(cmake --version | head -n1 | awk '{print $3}')
        echo "CMake version: $CMAKE_INSTALLED"
        if [[ "$(printf '%s\n' "3.30.1" "$CMAKE_INSTALLED" | sort -V | head -n1)" != "3.30.1" ]]; then
          echo "ERROR: CMake version must be >= 3.30.1, got $CMAKE_INSTALLED"
          exit 1
        fi

    - name: Install FAISS
      shell: bash
      run: |
        # Clone and build FAISS
        git clone --depth 1 --branch v1.7.4 https://github.com/facebookresearch/faiss.git /tmp/faiss
        cd /tmp/faiss
        cmake -B build \
          -DFAISS_ENABLE_GPU=OFF \
          -DFAISS_ENABLE_PYTHON=OFF \
          -DBUILD_TESTING=OFF \
          -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j $(nproc)
        sudo cmake --install build

    - name: Build native library
      shell: bash
      run: |
        cd paimon-faiss-jni
        ./scripts/build-native.sh --clean --fat-lib

    - name: Build paimon-faiss-jni
      shell: bash
      run: |
        mvn -B clean install -pl paimon-faiss-jni -am -DskipTests -Ppaimon-faiss-vector

    - name: Build paimon-faiss
      shell: bash
      run: |
        mvn -B clean install -pl paimon-faiss -am -DskipTests -Ppaimon-faiss-vector
